### ISSUE TITLE
Very high memory and CPU usage on Server

### ISSUE THREAD

**Issue by Dulciphi** [HostileNetworks/ReignModpack#11]
Unsure of cause - suspect village/villagers.

I was at the local village just after Emaps had logged off. I was there when it was getting dark so I used the bed there rather than rush home. 

Upon waking, I started getting 'internal server error' message.

Server log has this from the same time:

````[12:50:16] [User Authenticator #6/INFO]: UUID of player Dulciphi is 208cbb56-cb77-498b-9667-a8bb9dcdec2e
[12:50:16] [Server thread/WARN]: Invalid statistic in ./world/stats/208cbb56-cb77-498b-9667-a8bb9dcdec2e.json: Don't know what playTime is
[12:50:19] [Server thread/INFO]: Dulciphi[/124.191.93.148:61976] logged in with entity id 10150 at (250.61057281470838, 66.0, 546.6051992339529)
[12:50:19] [Server thread/INFO]: Dulciphi joined the game
[12:50:24] [Server thread/WARN]: Failed to handle packet for /124.191.93.148:61976
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~w.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75114_a(I)V
at enviromine.handlers.EM_StatusManager.getSurroundingData(EM_StatusManager.java:596) ~[EM_StatusManager.class:?]
at enviromine.trackers.EnviroDataTracker.updateData(EnviroDataTracker.java:121) ~[EnviroDataTracker.class:?]
at enviromine.handlers.EM_StatusManager.updateTracker(EM_StatusManager.java:88) ~[EM_StatusManager.class:?]
at enviromine.handlers.EM_EventManager.onLivingUpdate(EM_EventManager.java:1201) ~[EM_EventManager.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_790_EM_EventManager_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287) ~[ForgeHooks.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560) ~[sv.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~w.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
... 2 more
````

I'd log back in and take a few steps before getting kicked again with the same error. 

Checking the server (MineOS) showed me that the RAM was maxed out (18KB left) and CPU was hammered, close to 100%.  I restarted the server, then tried to relog.

I still got the same error-disconnect, but I was able to eventually get out of the village just by taking a few steps each time I logged in. 

Once clear of the village, CPU usage started to go down but it was still much higher than usual. Well over 50% with occasional peaks over 80%. It was still well over 50% by the time I made it back to my base, so I just disconnected. RAM usage stayed low/normal after the relog.

**Comment by cosmicdan** [comment]
That error is fixed. If it happens again we'll WarmRoast it.
