### ISSUE TITLE
Crash with AW2 combat AI - Ticking entity at .ai.EntityAIHurtByTarget.func

### ISSUE THREAD

**Issue by Dulciphi** [HostileNetworks/ReignModpack#5]
I can't be certain which entity was attacking the soldier at the time. There were many. This test was conducted with the a newly updated Targeting List (not the one on the repo) that added Special Mobs. 

[19:46:06] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.entity.EntityLivingBase.func_142014_c(EntityLivingBase.java:2039) ~[sv.class:?]
    at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:35) ~[vn.class:?]
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94) ~[uj.class:?]
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537) ~[sw.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774) ~[sv.class:?]
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367) ~[sw.class:?]
    at net.shadowmage.ancientwarfare.npc.entity.NpcPlayerOwned.func_70636_d(NpcPlayerOwned.java:342) ~[NpcPlayerOwned.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206) ~[sw.class:?]
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:759) ~[NpcBase.class:?]
    at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
    at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
    ... 4 more
[19:46:06] [Server thread/ERROR]: This crash report has been saved to: D:\Storage\Minecraft\1710temp\MultiMC\instances\1.7.10\minecraft\crash-reports\crash-2016-08-05_19.46.06-server.txt
[19:46:06] [Server thread/INFO]: Stopping server
[19:46:06] [Server thread/INFO]: Saving players
[19:46:06] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 8/5/16 7:46 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.minecraft.entity.EntityLivingBase.func_142014_c(EntityLivingBase.java:2039)
    at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:35)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.shadowmage.ancientwarfare.npc.entity.NpcPlayerOwned.func_70636_d(NpcPlayerOwned.java:342)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:759)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.EntityLivingBase.func_142014_c(EntityLivingBase.java:2039)
    at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:35)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:537)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.shadowmage.ancientwarfare.npc.entity.NpcPlayerOwned.func_70636_d(NpcPlayerOwned.java:342)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:759)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
    Entity Type: AncientWarfareNpc.aw_npc_combat (net.shadowmage.ancientwarfare.npc.entity.NpcCombat)
    Entity ID: 123220
    Entity Name: Soldier
    Entity's Exact location: 167.29, 74.30, 221.93
    Entity's Block location: World: (167,74,221), Chunk: (at 7,4,13 in 10,13; contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.07, -0.35, 0.00
Stacktrace:
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
    Level name: NewRTG+Stellar
    All players: 1 total; [GCEntityPlayerMP['<PROFILE NAME>'/880, l='NewRTG+Stellar', x=169.13, y=76.40, z=220.47]]
    Chunk stats: ServerChunkCache: 901 Drop: 0
    Level seed: -7933258971330979753
    Level generator: ID 05 - RTG, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-48,89,-64), Chunk: (at 0,5,0 in -3,-4; contains blocks -48,0,-64 to -33,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 168459 game time, 567021 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 72821 (now: false), thunder time: 154925 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by cosmicdan** [comment]
Wait and see if it happens again with new auto-inject AI version.
