### ISSUE TITLE
AW2 Town Hall chunk loading stacktrace

### ISSUE THREAD

**Issue by cosmicdan** [HostileNetworks/ReignModpack#8]
What's this about?

````
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.Exception: Stack trace
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Thread.dumpStack(Thread.java:1329)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:781)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:479)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72964_e(World.java:419)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at CustomOreGen.Server.ServerState.chunkForced(ServerState.java:372)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at CustomOreGen.ForgeInterface.onForceChunk(ForgeInterface.java:74)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler_24_ForgeInterface_onForceChunk_ForceChunkEvent.invoke(.dynamic)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:741)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.shadowmage.ancientwarfare.npc.tile.TileTownHall.loadChunks(TileTownHall.java:74)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.shadowmage.ancientwarfare.npc.tile.TileTownHall.func_145845_h(TileTownHall.java:58)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at fastcraft.at.a(F:978)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at fastcraft.H.aq(F:36)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[12:39:04] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[12:39:46] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.Exception: Stack trace
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Thread.dumpStack(Thread.java:1329)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:781)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:479)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72964_e(World.java:419)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at CustomOreGen.Server.ServerState.chunkForced(ServerState.java:372)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at CustomOreGen.ForgeInterface.onForceChunk(ForgeInterface.java:74)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler_24_ForgeInterface_onForceChunk_ForceChunkEvent.invoke(.dynamic)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:741)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.shadowmage.ancientwarfare.npc.tile.TileTownHall.loadChunks(TileTownHall.java:74)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.shadowmage.ancientwarfare.npc.tile.TileTownHall.func_145845_h(TileTownHall.java:58)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at fastcraft.at.a(F:978)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at fastcraft.H.aq(F:36)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[12:39:49] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````

**Comment by MiscMC** [comment]
Hey can i add or make a res. for this

**Comment by cosmicdan** [comment]
Make a res? I don't follow.

On Jan 10, 2017, Autistic Siegmeier <notifications@github.com> wrote:
>Hey can i add or make a res. for this

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by cosmicdan** [comment]
Cannot reproduce, original reporter can not remember how either. Closing.
